Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -8,7 +8,7 @@ jobs:
   build-and-push:
     runs-on: ubuntu-latest
     permissions:
-      contents: read
+      contents: write
       packages: write   #imprescindible para poder publicar en ghcr.io
 
     steps:
@@ -34,3 +34,17 @@ jobs:
           # para reutilizar capas no modificadas entre ejecuciones
           cache-from: type=gha
           cache-to: type=gha,mode=max
+        # me permite usar el digest de la imagen para referenciarlo desde el main (push automatico del main)
+      - name: Update main.txt with new image digest
+        run: |
+          IMAGE_REF="ghcr.io/carlota-juarez/app-mne-bids@${{ steps.build.outputs.digest }}"
+          sed -i -E "s|docker://ghcr\.io/carlota-juarez/app-mne-bids(@sha256:[a-f0-9]+|:full)|docker://${IMAGE_REF}|" main.txt
+          grep -q "$IMAGE_REF" main.txt && echo "main.txt actualizado correctamente" || (echo "ERROR: main.txt no se actualizó" && exit 1)
+
+      - name: Commit updated main.txt
+        run: |
+          git config user.name "github-actions[bot]"
+          git config user.email "github-actions[bot]@users.noreply.github.com"
+          git add main.txt
+          git diff --staged --quiet || git commit -m "chore: pin image digest to latest build [skip ci]"
+          git push
